### ISSUE TITLE
Makefile Error

### ISSUE THREAD

**Issue by katrinaying** [openearth/lisflood-fp-bmi#1]
Hi,

Thanks for sharing. But I have encountered a problem.
I typed "make -f makefile" in Cygwin, but it shows the following error message:
make: *** No rule to make target 'lisflood_lin', needed by 'all'.  Stop.
Could you please help me with this problem? Thanks!

Katrina

**Comment by ChippChapp** [comment]
Hi Kartrina,

thanks for your interest.
I have no experience with Cygwin, but it seems to me that you try to compile Lisflood-FP in a Windows environment.
So far, we have tested the compilation only for Linux, so maybe that's the cause for your error message.

Hope this helps and let me know if it worked.

Best, Jannis

**Comment by katrinaying** [comment]
Hi Jannis,

Thanks for responding! It is really helpful.
I can successfully compile it in the Linux system now.

Katrina
